# Generated by Django 5.1.4 on 2025-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='xodimlar/'),
        ),
    ]
