# Generated by Django 5.1.4 on 2025-01-05 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('brend', models.CharField(max_length=255)),
                ('narxi1', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('narxi2', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('miqdor', models.FloatField()),
                ('olchov', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('dokon', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('manzil', models.TextField(blank=True, null=True)),
                ('qarz', models.FloatField(default=0)),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bolim')),
            ],
        ),
    ]
