# Generated by Django 5.1.4 on 2025-01-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulot',
            old_name='narxi1',
            new_name='narx1',
        ),
        migrations.RenameField(
            model_name='mahsulot',
            old_name='narxi2',
            new_name='narx2',
        ),
    ]
