# Generated by Django 5.1.4 on 2025-01-11 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_narxi1_mahsulot_narx1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='sana',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
