# Generated by Django 5.1.4 on 2025-01-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mijoz_sana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mijoz',
            name='sana',
        ),
    ]
